spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
kakao:
  api:
    key: "2573ecdca19c0b24e9bddc7d85b04084"
    authUri: "https://kauth.kakao.com/oauth"
    redirectUri: "http://localhost:8080/kakao_login"